CREATE TABLE IF NOT EXISTS auditoria_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  empresa_id BIGINT NOT NULL,
  usuario_id BIGINT NULL,
  usuario_nombre VARCHAR(255) NOT NULL,
  accion VARCHAR(80) NOT NULL,
  entidad VARCHAR(80) NOT NULL,
  entidad_id VARCHAR(100) NULL,
  descripcion VARCHAR(500) NOT NULL,
  datos_anteriores JSON NULL,
  datos_nuevos JSON NULL,
  metodo_http VARCHAR(10) NULL,
  ruta VARCHAR(500) NULL,
  ip VARCHAR(64) NULL,
  user_agent VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_auditoria_empresa (empresa_id),
  INDEX idx_auditoria_usuario (usuario_id),
  INDEX idx_auditoria_accion (accion),
  INDEX idx_auditoria_entidad (entidad),
  INDEX idx_auditoria_created_at (created_at),
  INDEX idx_auditoria_empresa_created_at (empresa_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
