ALTER TABLE caja_chica
  MODIFY COLUMN estado
  ENUM('PENDIENTE','CONFIRMADO','ANULADO')
  NOT NULL DEFAULT 'PENDIENTE';

ALTER TABLE movimientos_bancarios
  MODIFY COLUMN estado
  ENUM('PENDIENTE','CONFIRMADO','ANULADO')
  NOT NULL DEFAULT 'PENDIENTE';
